### ISSUE TITLE
[Frontend]Need an official website for WASM-Cairo

### ISSUE THREAD

**Issue by cryptonerdcn** [cryptonerdcn/wasm-cairo#21]
WASM-Cairo needs a website that includes:
- A landing page.
- Intro page, with a playground.
- A document page(or link)

Maybe sth like: https://www.dojoengine.org/en/

I created an official site a long time ago: https://delicate-author-279911.framer.app/ 
However, I am not good at website design, and this site is too old.

___
You can contact me for any design resource(logo, banner, etc...).
You may create a new repo for this website.

**Comment by LeandroCarvajal** [comment]
hi @cryptonerdcn, i find this proposal very interesting, do you have a stack in mind?

**Comment by cryptonerdcn** [comment]
@LeandroCarvajal Hi! If you mean tech stack I prefer next.js+tailwind.

**Comment by LeandroCarvajal** [comment]
I use react, but I would adapt quickly to next.js+tailwind. If you think I would like this issue

**Comment by cryptonerdcn** [comment]
@LeandroCarvajal Hi you can also look at this project:  https://github.com/StarknetAstro/AstroEditor
This is maintained by my friend now, he may also help us to do this work so maybe you can use this project’s tech stack.

**Comment by LeandroCarvajal** [comment]
@cryptonerdcn hi, of course, I had not seen it and it seems to me very good project.
If you are ok with it we could set up a group on telegram.

**Comment by cryptonerdcn** [comment]
@SimplementeCao Of Course. You can DM me on the telegram. My handle is as same as my Github's name.

**Comment by cryptonerdcn** [comment]
Hi @SimplementeCao, any new info?

**Comment by SimplementeCao** [comment]
Hi @cryptonerdcn sorry for the delay, this week I will upload the main page, again a thousand apologies.

**Comment by YanYuanFE** [comment]
Hi, @cryptonerdcn , this is my work, https://wasm-cairo-landing.vercel.app/

**Comment by cryptonerdcn** [comment]
Hi @YanYuanFE, it seems good! Can you upload it to Github?
